FROM golang:1.17

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o main cmd/users/main.go

# Expose port 9001 to the outside world
EXPOSE 9001

# Run the executable
CMD ["./main"]